name: Translations - sync translation from crowdin to github

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Target language'
        required: true
        default: ru
        type: choice
        options:
          - ru
          - ja
          - ko
          - zh-CN
#      crowdinBranch:
#        description: 'New Crowdin branch to create (without lang suffix)'
#        required: true
#        default: release-candidate
#        type: string
#      originBranch:
#        description: 'Branch that is being translated'
#        required: true
#        default: main
#        type: string
      newBranch:
        type: boolean
      onlyTranslated:
        description: 'Pull only fully translated and approved files'
        required: true
        type: boolean

jobs:
  sync-translations:
    name: Sync Translations for release-candidate-${{ matrix.lang }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup env vars
        env:
          crowdinBranch: ${{ inputs.language && format('translation-{0}', inputs.language) || 'main' }}
        run: >
          echo "crowdinBranch=$crowdinBranch" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Crowdin CLI
        run: npm install -g @crowdin/cli

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull translations
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: >
          crowdin pull translations
            -c crowdin-oss.yml -b ${{ env.crowdinBranch }} 
            -l ${{ inputs.language }}
            --all
            ${{ inputs.onlyTranslated && '--skip-untranslated-files --export-only-approved' || ''}

      - name: Make a git commit
        run: |
          git add i18n/${{ inputs.language }}
          git commit -m "chore: update ${{ inputs.language }} translations"
          git push -u origin l10n-release-candidate-${{ matrix.lang }} || true


      - name: Commit and push translations
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git stash --include-untracked
          git checkout -b l10n-release-candidate-${{ matrix.lang }}
          git pull --rebase origin l10n-release-candidate-${{ matrix.lang }} || true
          crowdin download --export-only-approved --branch main --config crowdin-oss.yml --language=${{ matrix.lang }}
          git add i18n/${{ matrix.lang }}
          git commit -m "chore: update ${{ matrix.lang }} translations"
          git push -u origin l10n-release-candidate-${{ matrix.lang }} || true
          gh pr create -B release-candidate-${{ matrix.lang }} -H l10n-release-candidate-${{ matrix.lang }} --title "chore: update `${{ matrix.lang }}` translations" --body 'This automated PR updates only the fully translated `${{ matrix.lang }}` files.' || true

