name: Translations - Pull from crowdin to github

on:
  issue_comment:
    types: [created]

jobs:
  params:
    name: Check if comment author has requested Crowdin synchronization
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.check.outputs.command }}
      issue_number: ${{ github.event.issue.number }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event.comment.body }}" =~ ^/pull ]]
          then
            echo "::set-output name=command::pull"
          elif [[ "${{ github.event.comment.body }}" =~ ^/preview ]]
          then
            echo "::set-output name=command::preview"
          fi

  pull-translations:
    needs: params
    if: needs.params.outputs.command == 'pull'

    name: "Pull Translations for !${{ needs.params.outputs.issue_number }} from Crowdin to Github"
    runs-on: ubuntu-latest

    steps:
      - name: Env vars update
        run: |
          echo "language=ru" >> $GITHUB_ENV
          echo "issueNumber=${{ needs.params.outputs.issue_number }}" >> $GITHUB_ENV
          echo "translationBranch=${{ format('translation-{0}-{1}', needs.params.outputs.issue_number, 'ru') }}" >> $GITHUB_ENV
          echo "translationBranchPreview=${{ format('translation-{0}-{1}-draft', needs.params.outputs.issue_number, 'ru') }}" >> $GITHUB_ENV

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.issueNumber }}
          body: |
            Started workflow: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}

      - name: Setup / Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.translationBranch }}

      - name: Setup / Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup / Crowdin CLI
        run: npm install -g @crowdin/cli

      - name: Setup / Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull translations
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run:
          crowdin pull translations
            -c crowdin-oss.yml
            -b ${{ env.translationBranch }}
            -l ${{ env.language }}
            --skip-untranslated-files --export-only-approved

      - name: Prepare commit
        id: prepare-commit
        run: |
          git add i18n/
          
          if [ -z "$(git diff --cached --name-only)" ]; then
            echo "staged_files=false" >> $GITHUB_OUTPUT
          else
            echo "staged_files=true" >> $GITHUB_OUTPUT
          fi

      - name: Create comment if no staged files
        if: steps.prepare-commit.outputs.staged_files == 'false'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.issueNumber }}
          body: |
            There is nothing to commit, possible reasons:
            
              * there is no fully translated and approved files
              * there is no difference with the current state of the branch

      - name: Commit
        if: steps.prepare-commit.outputs.staged_files == 'true'
        run: |
          git commit -m "chore: update ${{ env.language }} translations !${{ env.issueNumber }}"
          git push -u origin ${{ env.translationBranch }}

#  deploy-preview:
#    uses: ./.github/workflows/deploy.yml
#    secrets: inherit
